#!/bin/bash -x
function HINT {
  :
}

clear
ln -s ./amboso ./anvil
HINT " STEP 0/9    We symlinked the script to anvil to avoid referring to many places around here as amboso.

    try_amboso    a tester for amboso functions

    This script shows usage of amboso by Bash stacktrace.
    Every time the script runs a command, it will repeat it to us, in this format:
    Every + sign is a command being run.

    \"+    CMD_LINE\"
    \"CMD OUTPUT . . .\"
    \"HINT an hint, when there is one\"
    \":\"
    \"read                Which mean the shell is waiting for an Enter to proceed.\"


    This allows us to test program behaviour for different run modes.

    [Press Enter to continue] "
read </dev/tty
clear

cd .
pwd
ls -lA
HINT " STEP 1/9

    cd to project dir (we are here already!), we will test how amboso behaves when it runs without any flags.

    It seems our repo already has a compliant ./bin dir... We will make sure to disrupt that peace soon.
    We will rename the directory to ./some_bin_name, and even though it contains a stego.lock file, it may cause some little trouble.

    Please dont get out of the script before we reach step 4. Idempotency, right? 2 more steps left. Or you will have to do that mv all by yourself, no help.

    [Press Enter to continue] "
read </dev/tty
clear


mv ./bin/ ./some_bin_name/
HINT " STEP 2/9

    We renamed the compliant bin folder.

    [Press Enter to continue], two times real fast if youre bored.  :)  "
read </dev/tty
clear

./anvil
HINT " STEP 3/9

    No args run, no -D provided. ./bin does not exist, right? (hence does not contain a valid stego.lock file. Who cares its actually there if you didnt tell amboso in which directory it is?)

    [Press Enter to continue] "
read </dev/tty
clear

mv ./some_bin_name/ ./bin/
HINT " STEP 4/9

    NOW we rename back our compliant directory to ./bin, and it also contains a stego.lock file!

    [Press Enter to continue] "
read </dev/tty
clear

./anvil
HINT " STEP 5/9

    No args run, no -D provided. ./bin does exist now ( and the contained stego.lock file will be used to set -SEDM flags ), so we get an error for not giving a version query as argument.

    [Press Enter to continue] "
read </dev/tty
clear

./anvil -v 0.1.0
HINT " STEP 6/9

    Verbose query, should succeed in reporting unbuilt version

    [Press Enter to continue] "
read </dev/tty
clear

./anvil -rbp 0.1.0
HINT " STEP 7/9

    Build, run, purge 0.1.0. Tests single file compilation & execution. Purge done just before quitting

    [Press Enter to continue] "
read </dev/tty
clear

./anvil -rb 0.9.0
HINT " STEP 8/9

    Build, run 0.9.0. Tests make compilation & execution. No purge done, binary stays in the directory for future queries

    [Press Enter to continue] "
read </dev/tty
clear

./anvil -prbiv 0.1.0
rm ./anvil # We remove the symlink, you should put your own one outside of the repo dir.
HINT " STEP 9/9

    Verbose Init, Build, Run and Purge 0.1.0.
    Tests compilation for ALL tags & executes 0.1.0.
    Init is done as the first operation, trying to build all tags.
    We can see 0.9.0 was not built again, as it was not purged after the last command builded it.
    Purge is done just before quitting, and always tests cleanup for ALL tags.

    [Press Enter to continue, end of testing.] "
read </dev/tty

clear
