#!/bin/bash
#  Bash script to call amboso as a silent command interface.
#    Copyright (C) 2023-2025  jgabaut
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

flags="$1"
query="$2"

#Must always add B to not use git mode
echo -e "[API]    Add B to the flags to not use git mode by default.\n"

start_t_call=`date +%s.%N`
"./amboso" -s -V 5 -"$flags" "$query"
res="$?"
end_t_call=`date +%s.%N`
runtime_call=$( echo "$end_t_call - $start_t_call" | bc -l )
display_zero=$(echo $runtime_call | cut -d '.' -f 1)
  if [[ -z $display_zero ]]; then {
    display_zero="0"
  } else {
    display_zero=""
  }
  fi

if [[ $res -eq 0 ]] ; then {
  header="\033[1;32m[API]\e[0m"
} elif [[ $res -gt 1 ]] ; then {
  header="\033[1;34m[API]\e[0m"
} else {
  header="\033[1;31m[API]\e[0m"
}
fi

echo -e "$header    Got ($res), Operation was: [$flags] Query was: [$query] ).\n"
echo -e "$header    Took $display_zero$runtime_call seconds.\n"

exit "$res"

