name: (anviltest) base init -> purge mode
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Run ./amboso as base init -> purge mode, +verbose (-Bip -V 2)
      run: ./amboso -Bip -V 5
