name: Makefile CI

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check git tags
      run: git tag -l

    - name: Run aclocal
      run: aclocal
    - name: Run autoconf
      run: autoconf
    - name: Run automake --add-missing
      run: automake --add-missing
    - name: Run ./configure
      run: ./configure
    - name: Run make
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
