name: Test try_anvil_auto
on:
  push:
    branches: [ "master" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout new tags to branches
      id: checkout-tags
      uses: chachako/checkout-tags@v1
      with:
        base: jgabaut/amboso

    - name: Echo all new branches
      run: |
        while read branch; do
          echo $branch
        done <<< "${{ steps.checkout-tags.outputs.branches }}"
        git tag

    - name: List tags
      run: git tag

    - name: Install dependencies
      run: |
        pwd
        ls
        git status
        git describe --tags --abbrev=0
        git checkout $(git describe --tags --abbrev=0)

    - name: (try_anvil_auto) Testing try_anvil, without the stepping
      run: |
        ./try_anvil_auto || echo -e "\033[1;31mFailed.\e[0m\n"
